# Generated by Django 5.1.7 on 2025-03-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("local_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("symptoms", models.TextField()),
                ("prevention_methods", models.TextField()),
                ("treatment_methods", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_crops",
                    models.ManyToManyField(
                        related_name="susceptible_diseases", to="crops.crop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("local_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("symptoms", models.TextField()),
                ("prevention_methods", models.TextField()),
                ("treatment_methods", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_crops",
                    models.ManyToManyField(
                        related_name="susceptible_pests", to="crops.crop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("confidence_score", models.FloatField()),
                ("detection_date", models.DateTimeField(auto_now_add=True)),
                ("recommendation", models.TextField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pest_detection.disease",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pest_detection.pest",
                    ),
                ),
            ],
        ),
    ]
